In [9]:
import argparse
import os
import numpy as np
import glob
import pandas as pd
from sklearn.linear_model import LogisticRegression
import joblib
from sklearn.linear_model import LinearRegression

In [ ]:
parser = argparse.ArgumentParser()
parser.add_argument('--regularization', type=float, dest='reg', default=0.01, help='regularization rate')
args = parser.parse_args()

In [35]:
# load train and test set into numpy arrays
data = pd.read_csv("diabetes.csv")
display(data)
print(data.shape)
feature_names = data.iloc[:,0:8].columns
target_name = data.iloc[:1,8:].columns
data_features = data[feature_names]
data_target = data[target_name]
print(feature_names)
print(target_name)

from sklearn.model_selection import train_test_split
np.random.seed(123)
X_train, X_test, y_train, y_test = train_test_split(data_features.to_numpy(dtype=np.uint8), data_target.to_numpy(dtype=np.uint8), train_size = 0.70, test_size = 0.30, random_state = 1)
y_train = y_train.reshape(-1)
y_test = y_test.reshape(-1)

print(X_train.shape, y_train.shape, X_test.shape, y_test.shape, sep = '\n')

print(X_test)
print(y_test)


Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

(768, 9)
Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')
Index(['Outcome'], dtype='object')
(537, 8)
(537,)
(231, 8)
(231,)
[[  7 136  74 ...  26   0  51]
 [  1 151  60 ...  26   0  22]
 [  6 109  60 ...  25   0  27]
 ...
 [  1  91  54 ...  25   0  23]
 [ 10 168  74 ...  38   0  34]
 [  9 112  82 ...  34   0  36]]
[0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 1 0 1 1 0 0 1 0 1 0
 0 0 0 0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 1 1 0 1 1 0 0 0
 1 1 1 0 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 1
 0 0 0 1 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 1 1 0 0
 1 0 0 1 0 0 1 1 0 0 0 0 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 0 1 0 0 0 1 0 0 1 0
 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 1 1 0 0 0 1 0 0 1 1 0 1 1 0 0 1 0 0
 0 1 1 0 0 0 0 1 1]


In [37]:

#print('Train a logistic regression model with regularization rate of', args.reg)
#clf = LogisticRegression(C=1.0/args.reg, solver="liblinear", multi_class="auto", random_state=42)
#clf = LogisticRegression(solver="liblinear", multi_class="auto", random_state=42)
clf = LinearRegression()
clf.fit(X_train, y_train)

print(clf.coef_)
print(clf.intercept_)

print(type(clf.coef_))
print(type(clf.intercept_))


print('Predict the test set')
print(X_test.shape)
y_hat = clf.predict(X_test)
print(y_hat)
print(y_hat.shape)

y_hat_class = lambda k: 1 * (k > 0.5)
predicted_classes = y_hat_class(y_hat)
print(predicted_classes)

# calculate accuracy on the prediction
#acc = np.average(y_hat == y_test)
acc = np.average(predicted_classes == y_test)
print('Accuracy is', acc)

#run.log('regularization rate', np.float(args.reg))
#run.log('accuracy', np.float(acc))

#os.makedirs('outputs', exist_ok=True)
# note file saved in the outputs folder is automatically uploaded into experiment record
#joblib.dump(value=clf, filename='outputs/diabetes-sklearn-model.pkl')

[ 0.01621604  0.00563573 -0.00282196 -0.00067513  0.00014646  0.01444952
  0.03348406  0.00326321]
-0.7674837863180632
<class 'numpy.ndarray'>
<class 'numpy.float64'>
Predict the test set
(231, 8)
[ 4.47992276e-01  3.77888306e-01  2.05905680e-01  1.60307590e-02
  2.90910570e-01  3.19562787e-01  3.93412650e-01  1.61751068e-01
  2.17833801e-01  3.01000012e-01  4.26116668e-01  5.05287478e-02
  9.87422317e-01  6.66678038e-01 -1.83554929e-01  6.53406605e-01
  2.88816449e-01  3.38143605e-01  2.15829088e-01  1.76143826e-01
  3.94939946e-01  1.25898449e-01  9.43999302e-01  3.25142412e-01
  5.40459396e-02  4.47341320e-01  2.88990804e-01  5.89406435e-01
  7.57156675e-02  4.19512498e-01  3.79615117e-01  3.62859705e-01
  7.68224894e-04  7.17918201e-01  1.30339029e-01  6.38968569e-01
  5.83860472e-02  2.25273267e-01  1.19179061e-01  5.74207174e-01
  2.64384191e-01  1.04678651e-01 -7.43033849e-02  2.77922454e-01
  4.13130211e-02 -1.12548763e-01  7.58245133e-01  7.23258246e-01
  8.21666700e-02  2.157

In [53]:
coeffs = np.asarray(clf.coef_)
print(coeffs)
coeffs = coeffs.reshape(1,-1)
print(type(coeffs))
print(coeffs.shape)

c = np.asarray(coeffs)
print(c)

intercept = np.asarray(clf.intercept_)
print(intercept)
intercept = intercept.reshape(-1)
print(type(intercept))
print(intercept.shape)

i = np.asarray(intercept)
print(i)

[ 0.01621604  0.00563573 -0.00282196 -0.00067513  0.00014646  0.01444952
  0.03348406  0.00326321]
<class 'numpy.ndarray'>
(1, 8)
[[ 0.01621604  0.00563573 -0.00282196 -0.00067513  0.00014646  0.01444952
   0.03348406  0.00326321]]
-0.7674837863180632
<class 'numpy.ndarray'>
(1,)
[-0.76748379]


In [54]:
import os
import pandas as pd

data = pd.read_csv("diabetes-test.csv")
print(data.shape)
feature_names = data.iloc[:,0:8].columns
target_name = data.iloc[:1,8:].columns
print(feature_names)
print(target_name)

data_features = data[feature_names]
X_test = data_features.to_numpy(dtype=np.uint8)
data_target = data[target_name]
y_test = data_target.to_numpy(dtype=np.uint8).reshape(-1)

print(X_test)
print(y_test)

(50, 9)
Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')
Index(['Outcome'], dtype='object')
[[  6 148  72  35   0  33   0  50]
 [  1  85  66  29   0  26   0  31]
 [  8 183  64   0   0  23   0  32]
 [  1  89  66  23  94  28   0  21]
 [  0 137  40  35 168  43   2  33]
 [  5 116  74   0   0  25   0  30]
 [  3  78  50  32  88  31   0  26]
 [ 10 115   0   0   0  35   0  29]
 [  2 197  70  45  31  30   0  53]
 [  8 125  96   0   0   0   0  54]
 [  4 110  92   0   0  37   0  30]
 [ 10 168  74   0   0  38   0  34]
 [ 10 139  80   0   0  27   1  57]
 [  1 189  60  23  78  30   0  59]
 [ 10  92  62   0   0  25   0  31]
 [ 13 104  72   0   0  31   0  38]
 [  5 104  74   0   0  28   0  48]
 [  2  94  76  18  66  31   0  23]
 [  7  97  76  32  91  40   0  32]
 [  1 100  74  12  46  19   0  28]
 [  0 102  86  17 105  29   0  27]
 [  4 128  70   0   0  34   0  24]
 [  6 147  80   0   0  29   0  50]
 [

In [56]:
#random_index = np.random.randint(0, len(X_test)-1)
random_index = 5
print("Random index = ", random_index)
#print(X_test[random_index])
#print(X_test[random_index].tolist())


single_sample = X_test[random_index].reshape(1,-1)
print("single sample")
print(single_sample)
print(single_sample.tolist())

y_pred = clf.predict(single_sample)
print(y_pred)
if y_pred > 0.5:
  pred_class = 1
else:
  pred_class = 0

print(pred_class)

print(y_test[random_index])

#y_pred_prob = clf.predict_proba(single_sample)
#print(y_pred_prob)


Random index =  5
single sample
[[  5 116  74   0   0  25   0  30]]
[[5, 116, 74, 0, 0, 25, 0, 30]]
[0.21765048]
0
0
